music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.AlbumListenView.as_view(), name='listen'),
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='add-album'),
    url(r'^album/edit/(?P<pk>[0-9]+)$', views.AlbumUpdate.as_view(),
        name='edit-album'),
    url(r'^album/delete/(?P<pk>[0-9]+)$', views.AlbumDelete.as_view(),
        name='delete-album'),
    url(r'^song/add/(?P<album_id>[0-9]+)$', views.SongCreate.as_view(),
        name='add-song'),
    url(r'^song/edit/(?P<pk>[0-9]+)$', views.SongUpdate.as_view(),
        name='edit-song'),
    url(r'^song/delete/(?P<pk>[0-9]+)$', views.SongDelete.as_view(),
        name='delete-song'),
    url(r'^search/$', views.AlbumSearchView.as_view(), name='search'),
    url(r'^frontpage/(?P<page>[0-9]+)$',
        views.get_frontpage_videos,
        name='frontpage'),
]

orpheus/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = i18n_patterns(
    # url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^media/', include('media_common.urls', namespace="media")),
    url(r'^videos/', include('videos.urls', namespace="videos")),
    url(r'^music/', include('music.urls', namespace="music")),
    url(r'^stats/', include('stats.urls', namespace="stats")),
    url(r'^$', views.index, name='index'),
)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

handler404 = 'orpheus.views.page_not_found_view'
handler500 = 'orpheus.views.error_view'
handler403 = 'orpheus.views.permission_denied_view'
handler400 = 'orpheus.views.bad_request_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

music/models.py
import os
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django_cleanup.signals import cleanup_post_delete

from accounts.models import OrpheusUser
from media_common.models import Media
from orpheus.settings import STATIC_URL, MEDIA_ROOT
from orpheus.utils import remove_empty_dir


def thumbnail_upload_path(instance, filename):
    return os.path.join("music/thumbnails/%s/" % instance.id, filename)


class Album(Media):
    thumbnail = models.FileField(_("Thumbnail"),
                                 upload_to=thumbnail_upload_path,
                                 blank=True)

    def get_absolute_url(self):
        return reverse('music:listen', kwargs={'pk': self.pk})

    @property
    def thumbnail_url(self):
        if self.thumbnail and hasattr(self.thumbnail, 'url'):
            return self.thumbnail.url
        else:
            return os.path.join(STATIC_URL, 'music/img/album-default.jpg')


# Receive the pre_delete signal and delete the files
# associated with the model instance.
@receiver(post_delete, sender=Album)
def album_delete(sender, instance, **kwargs):
    cleanup_post_delete.send(sender)
    remove_empty_dir(os.path.join(
        MEDIA_ROOT,
        thumbnail_upload_path(instance, "")))


def song_upload_path(instance, filename):
    return os.path.join("music/albums/%s/" % instance.album.id, filename)


class Song(models.Model):
    track_number = models.IntegerField(_("Track number"))
    title = models.TextField(_("Title"))
    source = models.FileField(_("Source"), upload_to=song_upload_path)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('music:listen', kwargs={'pk': self.album.pk})

    def __str__(self):
        return self.title

music/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from media_common.views import (
    MediaSearchView,
    MediaDetailView,
    MediaCreate,
    MediaUpdate,
    MediaDelete,
    MediaIndexView
)
from .models import Album, Song


class IndexView(MediaIndexView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        albums = Album.objects.all()
        return MediaIndexView.get_frontpage_media(albums)


def get_frontpage_videos(request, page):
    albums = Album.objects.all()
    all_albums = MediaIndexView.get_frontpage_media(albums, int(page))
    return render(request, 'music/album-list.html', {'all_albums': all_albums})


class AlbumListenView(MediaDetailView):
    model = Album
    template_name = 'music/listen.html'


class AlbumCreate(MediaCreate):
    model = Album
    fields = ['title', 'description', 'thumbnail', 'tags']


class AlbumUpdate(MediaUpdate):
    model = Album
    fields = ['title', 'description', 'thumbnail', 'tags']


class AlbumDelete(MediaDelete):
    model = Album


class SongCreate(CreateView):
    model = Song
    fields = ['title', 'source', 'track_number']

    def form_valid(self, form):
        song = form.save(commit=False)
        song.user = self.request.user
        song.album = Album.objects.get(pk=self.kwargs['album_id'])
        song.save()
        if self.request.is_ajax():
            return HttpResponse(song.get_absolute_url())
        else:
            return super(SongCreate, self).form_valid(form)


class SongUpdate(UpdateView):
    model = Song
    fields = ['title', 'track_number']

    def form_valid(self, form):
        song = form.save(commit=False)
        song.save()
        if self.request.is_ajax():
            return HttpResponse(song.get_absolute_url())
        else:
            return super(SongUpdate, self).form_valid(form)

    def get_object(self, queryset=None):
        song = super(SongUpdate, self).get_object()
        if (not song.album.user == self.request.user and
                not self.request.user.is_staff):
            raise Http404
        return song


class SongDelete(DeleteView):
    model = Song

    def get_success_url(self):
        song = super(SongDelete, self).get_object()
        album = song.album
        return reverse_lazy('music:listen',
                            kwargs={'pk': album.pk})

    def get_object(self, queryset=None):
        song = super(SongDelete, self).get_object()
        if (not song.album.user == self.request.user and
                not self.request.user.is_staff):
            raise Http404
        return song


class AlbumSearchView(MediaSearchView):
    template_name = 'music/search-result.html'
    model = Album

music/templates/music/album-list.html
{% for album in all_albums %}
    <div class="orpheus-media-block orpheus-album-block">
        <a href="{% url 'music:listen' album.id %}">
            <img src="{{ album.thumbnail_url }}" class="orpheus-media-block-thumbnail orpheus-album-block-thumbnail">
            <b>{{ album.title }}</b>
        </a>
        <br>
        <a href="{% url 'account_profile' album.user %}"><i>{{ album.user.full_name }}</i></a>
    </div>
{% endfor %}

music/templates/music/album_confirm_delete.html
{% extends "music/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans 'Delete album' %}{% endblock %}

{% block page_body %}
    {% include 'orpheus/form-confirm-delete.html' %}
{% endblock %}

music/templates/music/album_form.html
{% extends "music/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans 'Album' %}{% endblock %}

{% block page_body %}
    <form action="" method="post" enctype="multipart/form-data" class="pure-form pure-form-stacked validated-form">
        {% csrf_token %}
        {% include 'orpheus/form-template.html' %}
        <button class="pure-button" type="submit">{% trans 'Submit' %}</button>
    </form>
{% endblock %}

music/templates/music/base.html
{% extends "media_common/base-common.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans 'Music' %}{% endblock %}

{% block media_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/css/base.css' %}" />
    {% block page_css %}{% endblock %}
{% endblock %}


{% block media_js%}
    {% block page_js %}{% endblock %}
{% endblock %}


{% block orpheus-navbar-music %}orpheus-navbar-selected{% endblock %}


{% block media_common_body %}
    {% block page_body %}{% endblock %}
{% endblock %}


{% block search_action %}{% url 'music:search' %}{% endblock %}

music/templates/music/index.html
{% extends "music/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page_css %}
{% endblock %}

{% block page_js %}
    {% url 'music:frontpage' 0 as album_list_url %}
    {% include 'media_common/frontpage-load-more.html' with media_list_url=album_list_url %}
{% endblock %}

{% block page_body %}
    <div class="orpheus-media-block-container">
        {% include 'music/album-list.html' %}
    </div>
    <button class="pure-button frontpage-load-more">{% trans "Load more" %}</button>
{% endblock %}

music/templates/music/listen.html
{% extends "music/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{{ album.title }}{% endblock %}

{% block page_css %}
    <link rel="stylesheet" href="{% static 'orpheus/addons/player/mediaelementplayer.min.css' %}" />
    <link rel="stylesheet" href="{% static 'orpheus/addons/comments/jquery-comments.css' %}" />
    <link rel="stylesheet" href="{% static 'music/css/listen.css' %}" />
{% endblock %}

{% block page_js %}
    <script src="{% static 'orpheus/addons/player/mediaelement-and-player.js' %}"></script>
    {% with album as media %}
        {% include 'media_common/voting-initialization.html' %}
        {% include 'media_common/comments-initialization.html' %}
        {% include 'music/music-player-initialization.html' with album=album%}
    {% endwith %}
    <script src="{% static 'music/js/watch.js' %}"></script>
{% endblock %}

{% block page_body %}
    <h1>{{ album.title }}</h1>
    {% if album.user == user or user.is_staff %}
        <a href="{% url 'music:edit-album' album.id %}"><button class="pure-button">{% trans 'Edit album' %}</button></a>
        <a href="{% url 'music:delete-album' album.id %}"><button class="pure-button">{% trans 'Delete album' %}</button></a>
        <br><br><br>
    {% endif %}

    {% if album.user == user %}
        <a href="{% url 'music:add-song' album_id=album.id %}"><button class="pure-button">{% trans 'Add songs' %}</button></a><br><br>
    {% endif %}

    <ul class="orpheus-album-playlist-container">
        {% for song in album.song_set.all|dictsort:"track_number" %}
            <li class="song-link" data-track-number="{{ song.track_number }}" data-url="{{ song.source.url }}">
                <span class="orpheus-album-song-link">{{ song.track_number }}.&nbsp;{{ song.title }}</span>
                {% if album.user == user or user.is_staff %}
                    <div class="orpheus-album-media-controls">
                        <a href="{% url 'music:edit-song' song.id %}"><button class="pure-button">{% trans 'Edit' %}</button></a>
                        <a href="{% url 'music:delete-song' song.id %}"><button class="pure-button">{% trans 'Delete' %}</button></a>
                    </div>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% if album.song_set.count > 0 %}
        <audio id="player" controls="controls" style="width:100%;" >
            <source id="player-source" src="{{ album.song_set.first.source.url }}" type="audio/mp3">
            <p>{% blocktrans %}Your browser does not support this audio.{% endblocktrans %}</p>
        </audio>
    {% endif %}
    {% url 'music:search' as search_url %}
    {% include 'media_common/media_info_box.html' with media=album search_url=search_url %}
    <div id="orpheus-comments-container"></div>
{% endblock %}

music/templates/music/music-player-initialization.html
{% load staticfiles %}
{% load i18n %}

<script>
    var current_track = -1;
    var playlist_elements = $('.song-link');
    var total_tracks = 0;
    var playlist = [];
    {% for song in album.song_set.all|dictsort:"track_number" %}
        playlist.push("{{ song.source.url }}");
    {% endfor %}
    total_tracks = playlist.length;

    var current_element = null;
    var player = null;
    var keyboard_skip = 5; //seconds

    $('audio').mediaelementplayer({
        startLanguage:'en',
        translationSelector: true,
        keyActions: [
            {
                keys: [
                    37, // LEFT
                    227 // Google TV rewind
                ],
                action: function(player, media) {
                    if (!isNaN(media.duration) && media.duration > 0) {
                        if (player.isVideo) {
                                player.showControls();
                                player.startControlsTimer();
                        }

                        // keyboard_skip seconds
                        var newTime = Math.max(media.currentTime - keyboard_skip, 0);
                        media.setCurrentTime(newTime);
                    }
                }
            },
            {
                keys: [
                    39, // RIGHT
                    228 // Google TV forward
                ],
                action: function(player, media) {
                    if (!isNaN(media.duration) && media.duration > 0) {
                        if (player.isVideo) {
                            player.showControls();
                            player.startControlsTimer();
                        }

                        // keyboard_skip seconds
                        var newTime = Math.min(media.currentTime + keyboard_skip, media.duration);
                        media.setCurrentTime(newTime);
                    }
                }
            }
        ],
        success: function(mediaElement) {
            player = mediaElement;
        }
    });

    function play_next_song() {
        if (current_track != total_tracks) {
            player.setSrc(playlist[current_track]);
            player.load();
            player.play();
            current_track += 1;

            current_element.removeClass('selected-song');
            current_element = current_element.next();
            current_element.addClass('selected-song');
        }
    }

    playlist_elements.click(function() {
        current_element.removeClass('selected-song');
        current_element = $(this);
        current_element.addClass('selected-song');
        player.setSrc(current_element.data('url'));
        player.load();
        player.play();
        current_track = $(this).data('track-number');

        //Add event for playing next song if not at end
        if (current_track != total_tracks) {
            player.removeEventListener('ended', play_next_song);
            player.addEventListener('ended', play_next_song);
        }
    });

    $(window).on('load', function() {
        if (total_tracks > 0) {
            current_element = playlist_elements.first();
            current_element.addClass('selected-song');
            current_track = parseInt(current_element.data('track-number'));
            player.addEventListener('ended', play_next_song);
        }
    });
</script>

music/templates/music/search-result.html
{% extends "music/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans "Music search" %}{% endblock %}

{% block page_css %}
{% endblock %}

{% block page_js %}
{% endblock %}

{% block page_body %}
    <h3>{% blocktrans %}Results for {% endblocktrans %}"{{ request.GET.query }}":</h3>
    {% include 'media_common/pagination.html' %}
    <div class="orpheus-media-block-container">
        {% include 'music/album-list.html' with all_albums=results %}
    </div>
    {% if results.count == 0 %}
        <p>{% blocktrans %}No albums found.{% endblocktrans %}</p>
    {% endif %}
    {% include 'media_common/pagination.html' %}
{% endblock %}

music/templates/music/song_confirm_delete.html
{% extends "music/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans "Delete song" %}{% endblock %}

{% block page_body %}
    {% include 'orpheus/form-confirm-delete.html' %}
{% endblock %}

music/templates/music/song_form.html
{% extends "music/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans 'Song' %}{% endblock %}

{% block page_body %}
    <form action="" method="post" enctype="multipart/form-data" class="pure-form pure-form-stacked validated-form">
        {% csrf_token %}
        {% include 'orpheus/form-template.html' %}
        <button class="pure-button" type="submit">{% trans 'Submit' %}</button>
    </form>
{% endblock %}