accounts/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    # Account
    url(r'^profile/(?P<username>[\w.@+-]+)/$',
        views.profile_view,
        name="account_profile"),
    url(r'^profile/edit/(?P<slug>[\w.@+-]+)/$',
        views.OrpheusUserUpdate.as_view(),
        name='account_edit'),
    url(r'^login/$',
        views.OrpheusLoginView.as_view(),
        name="account_login"),
    url(r'^signup/$',
        views.OrpheusSignupView.as_view(),
        name="account_signup"),
    url(r'^logout/$',
        views.OrpheusLogoutView.as_view(),
        name="account_logout"),
    url(r'^password/change/$',
        views.OrpheusPasswordChangeView.as_view(),
        name="account_change_password"),
    url(r'^password/set/$',
        views.OrpheusPasswordSetView.as_view(),
        name="account_set_password"),
    url(r'^inactive/$',
        views.OrpheusAccountInactiveView.as_view(),
        name="account_inactive"),

    # E-mail
    url(r'^email/$',
        views.OrpheusEmailView.as_view(),
        name="account_email"),
    url(r'^confirm-email/$',
        views.OrpheusEmailVerificationSentView.as_view(),
        name="account_email_verification_sent"),
    url(r'^confirm-email/(?P<key>\w+)/$',
        views.OrpheusConfirmEmailView.as_view(),
        name="account_confirm_email"),

    # Password reset
    url(r'^password/reset/$',
        views.OrpheusPasswordResetView.as_view(),
        name="account_reset_password"),
    url(r'^password/reset/done/$',
        views.OrpheusPasswordResetDoneView.as_view(),
        name="account_reset_password_done"),
    url(r'^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$',
        views.OrpheusPasswordResetFromKeyView.as_view(),
        name="account_reset_password_from_key"),
    url(r'^password/reset/key/done/$',
        views.OrpheusPasswordResetFromKeyDoneView.as_view(),
        name="account_reset_password_from_key_done"),

    url(r'^', include('allauth.urls')),
]

music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.AlbumListenView.as_view(), name='listen'),
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='add-album'),
    url(r'^album/edit/(?P<pk>[0-9]+)$', views.AlbumUpdate.as_view(),
        name='edit-album'),
    url(r'^album/delete/(?P<pk>[0-9]+)$', views.AlbumDelete.as_view(),
        name='delete-album'),
    url(r'^song/add/(?P<album_id>[0-9]+)$', views.SongCreate.as_view(),
        name='add-song'),
    url(r'^song/edit/(?P<pk>[0-9]+)$', views.SongUpdate.as_view(),
        name='edit-song'),
    url(r'^song/delete/(?P<pk>[0-9]+)$', views.SongDelete.as_view(),
        name='delete-song'),
    url(r'^search/$', views.AlbumSearchView.as_view(), name='search'),
    url(r'^frontpage/(?P<page>[0-9]+)$',
        views.get_frontpage_videos,
        name='frontpage'),
]

orpheus/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = i18n_patterns(
    # url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^media/', include('media_common.urls', namespace="media")),
    url(r'^videos/', include('videos.urls', namespace="videos")),
    url(r'^music/', include('music.urls', namespace="music")),
    url(r'^stats/', include('stats.urls', namespace="stats")),
    url(r'^$', views.index, name='index'),
)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

handler404 = 'orpheus.views.page_not_found_view'
handler500 = 'orpheus.views.error_view'
handler403 = 'orpheus.views.permission_denied_view'
handler400 = 'orpheus.views.bad_request_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.VideoWatchView.as_view(), name='watch'),
    url(r'^add/$', views.VideoCreate.as_view(), name='add'),
    url(r'^edit/(?P<pk>[0-9]+)$', views.VideoUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>[0-9]+)$',
        views.VideoDelete.as_view(),
        name='delete'),
    url(r'^search/$', views.VideoSearchView.as_view(), name='search'),
    url(r'^frontpage/(?P<page>[0-9]+)$',
        views.get_frontpage_videos,
        name='frontpage'),
]

accounts/models.py
import os
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch.dispatcher import receiver
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django_cleanup.signals import cleanup_post_delete
from orpheus.settings import STATIC_URL, MEDIA_ROOT
from orpheus.utils import remove_empty_dir


class OrpheusUserManager(BaseUserManager):
    def create_user(self, username, full_name, email, password=None):
        user = self.model(
            username=username,
            full_name=full_name,
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, full_name, email, password):
        user = self.create_user(
            username=username,
            full_name=full_name,
            email=email,
            password=password,
        )
        user.is_admin = True
        user.save()
        return user


def profile_picture_upload_path(instance, filename):
    return os.path.join("accounts/profile_pictures/%s/" % instance.username, filename)


class OrpheusUser(AbstractUser):
    is_active = models.BooleanField(_("Is active"), default=True)
    is_admin = models.BooleanField(_("Is admin"), default=False)
    full_name = models.CharField(_("Full name"), max_length=100)
    profile_picture = models.FileField(_("Profile picture"),
                                       upload_to=profile_picture_upload_path,
                                       blank=True,
                                       null=True)

    objects = OrpheusUserManager()

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    @property
    def profile_picture_url(self):
        if self.profile_picture and hasattr(self.profile_picture, 'url'):
            return self.profile_picture.url
        else:
            return os.path.join(STATIC_URL, 'accounts/img/user-icon.png')

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.full_name

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('account_profile', kwargs={'username': self.username})

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


# Receive the post_save signal and add id to username
# This solves the problem of user impersonation by using
# visually similar unicode characters
@receiver(post_save, sender=OrpheusUser)
def orpheus_user_created(sender, instance, created, **kwargs):
    if created:
        instance.username = "%s_%s" % (instance.username, instance.id)
        instance.save()


# Receive the pre_delete signal and delete the files
# associated with the model instance.
@receiver(post_delete, sender=OrpheusUser)
def orpheus_user_delete(sender, instance, **kwargs):
    cleanup_post_delete.send(sender)
    remove_empty_dir(os.path.join(
        MEDIA_ROOT,
        profile_picture_upload_path(instance, "")))

accounts/forms.py
from django import forms
from django.forms import TextInput
from django.utils.translation import ugettext_lazy as _
from allauth.account.forms import LoginForm


class OrpheusSignupForm(forms.Form):
    full_name = forms.CharField(
        required=True,
        min_length=1,
        max_length=255,
        label=_("Full name"),
        widget=TextInput(attrs={'placeholder': _('Full name')})
    )

    def __init__(self, *args, **kwargs):
        super(OrpheusSignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.pop("autofocus", None)
        self.fields['email'].help_text = (
            _("You will use this e-mail to log in.")
        )
        self.fields['username'].help_text = (
            _("150 characters or fewer. Letters, digits"
              " and symbols @/./+/-/_ only.")
        )
        self.fields['password1'].min_length = 6
        self.fields['password2'].min_length = 6
        self.fields['password1'].help_text = (
            _("%(min)s characters or more.") %
            {'min': self.fields['password1'].min_length}
        )

    field_order = ['email', 'username', 'full_name', 'password1', 'password2']

    def signup(self, request, user):
        user.full_name = self.cleaned_data['full_name']
        user.save()


class LoginFormWithoutAutofocus(LoginForm):

    def __init__(self, *args, **kwargs):
        super(LoginFormWithoutAutofocus, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs.pop("autofocus", None)

accounts/views.py
from allauth.account import views
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic.edit import UpdateView
from .forms import LoginFormWithoutAutofocus
from .models import OrpheusUser
from videos.models import Video
from music.models import Album


def profile_view(request, username):
    orpheus_user = get_object_or_404(OrpheusUser, username=username)
    user_videos = Video.objects.filter(user=orpheus_user)
    user_albums = Album.objects.filter(user=orpheus_user)
    return render(request, 'accounts/profile.html',
                  {'orpheus_user': orpheus_user,
                   'user_videos': user_videos,
                   'user_albums': user_albums})


class OrpheusUserUpdate(UpdateView):
    model = OrpheusUser
    fields = ['full_name', 'profile_picture']
    slug_field = 'username'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.save()
        if self.request.is_ajax():
            return HttpResponse(user.get_absolute_url())
        else:
            return super(OrpheusUserUpdate, self).form_valid(form)

    def get_object(self, queryset=None):
        user = super(OrpheusUserUpdate, self).get_object()
        if not user == self.request.user and not self.request.user.is_staff:
            raise Http404
        return user


class OrpheusAccountInactiveView(views.AccountInactiveView):
    template_name = 'accounts/account_inactive.html'


class OrpheusEmailView(views.EmailView):
    template_name = 'accounts/email.html'


class OrpheusConfirmEmailView(views.ConfirmEmailView):
    template_name = 'accounts/email_confirm.html'


class OrpheusLoginView(views.LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginFormWithoutAutofocus


class OrpheusLogoutView(views.LogoutView):
    template_name = 'accounts/logout.html'


class OrpheusPasswordChangeView(views.PasswordChangeView):
    template_name = 'accounts/password_change.html'


class OrpheusPasswordResetView(views.PasswordResetView):
    template_name = 'accounts/password_reset.html'


class OrpheusPasswordResetDoneView(views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class OrpheusPasswordResetFromKeyView(views.PasswordResetFromKeyView):
    template_name = 'accounts/password_reset_from_key.html'


class OrpheusPasswordResetFromKeyDoneView(views.PasswordResetFromKeyDoneView):
    template_name = 'accounts/password_reset_from_key_done.html'


class OrpheusPasswordSetView(views.PasswordSetView):
    template_name = 'accounts/password_set.html'


class OrpheusSignupView(views.SignupView):
    template_name = 'accounts/signup.html'


class OrpheusEmailVerificationSentView(views.EmailVerificationSentView):
    template_name = 'accounts/verification_sent.html'

accounts/templates/accounts/account_inactive.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Account Inactive" %}{% endblock %}

{% block content %}
<h1>{% trans "Account Inactive" %}</h1>

<p>{% trans "This account is inactive." %}</p>
{% endblock %}

accounts/templates/accounts/base.html
{% extends "orpheus/master.html" %}
{% load staticfiles %}

{% block body %}
    {% block content %}{% endblock %}
    {% block extra_body %}{% endblock %}
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/base.css' %}" />
    {% block page_css %}{% endblock %}
{% endblock %}

{% block js %}
    {% block accounts_js %}{% endblock %}
{% endblock %}

accounts/templates/accounts/email.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Account" %}{% endblock %}

{% block content %}
    <h1>{% trans "E-mail Addresses" %}</h1>
{% if user.emailaddress_set.all %}
<p>{% trans 'The following e-mail addresses are associated with your account:' %}</p>

<form action="{% url 'account_email' %}" class="email_list pure-form pure-form-stacked" method="post">
{% csrf_token %}
<fieldset class="blockLabels">

  {% for emailaddress in user.emailaddress_set.all %}
<div class="ctrlHolder">
      <label for="email_radio_{{forloop.counter}}" class="{% if emailaddress.primary %}primary_email{%endif%}">

      <input id="email_radio_{{forloop.counter}}" type="radio" name="email" {% if emailaddress.primary or user.emailaddress_set.count == 1 %}checked="checked"{%endif %} value="{{emailaddress.email}}"/>

{{ emailaddress.email }}
    {% if emailaddress.verified %}
    <span class="verified">{% trans "Verified" %}</span>
    {% else %}
    <span class="unverified">{% trans "Unverified" %}</span>
    {% endif %}
      {% if emailaddress.primary %}<span class="primary">{% trans "Primary" %}</span>{% endif %}
</label>
</div>
  {% endfor %}

<div class="buttonHolder">
      <button class="secondaryAction pure-button" type="submit" name="action_primary" >{% trans 'Make Primary' %}</button>
      <button class="secondaryAction pure-button" type="submit" name="action_send" >{% trans 'Re-send Verification' %}</button>
      <button class="primaryAction pure-button" type="submit" name="action_remove" >{% trans 'Remove' %}</button>
</div>

</fieldset>
</form>

{% else %}
<p><strong>{% trans 'Warning:'%}</strong> {% trans "You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc." %}</p>

{% endif %}


    <h2>{% trans "Add E-mail Address" %}</h2>

    <form method="post" action="{% url 'account_email' %}" class="add_email pure-form pure-form-stacked validated-form">
        {% csrf_token %}
        {% include 'accounts/accounts-form.html' %}
        <button class="pure-button" name="action_add" type="submit">{% trans "Add E-mail" %}</button>
    </form>

{% endblock %}


{% block extra_body %}
<script type="text/javascript">
(function() {
  var message = "{% trans 'Do you really want to remove the selected e-mail address?' %}";
  var actions = document.getElementsByName('action_remove');
  if (actions.length) {
    actions[0].addEventListener("click", function(e) {
      if (! confirm(message)) {
        e.preventDefault();
      }
    });
  }
})();
</script>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}

{% load i18n %}
{% load account socialaccount %}

{% block head_title %}
    {% trans "Sign In" %}
{% endblock %}

{% block accounts_js %}
    {% include 'orpheus/message-initialization.html' with messages=form.non_field_errors %}
{% endblock %}

{% block orpheus-navbar-login %}orpheus-navbar-selected{% endblock %}

{% block content %}
    <h1>{% trans "Sign In" %}</h1>
    {% get_providers as socialaccount_providers %}
    {% if socialaccount_providers %}
        <p>
            {% blocktrans with site.name as site_name %}Please sign in with one
            of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
            for a {{ site_name }} account and sign in below:{% endblocktrans %}
        </p>
        <div class="socialaccount_ballot">
            <ul class="socialaccount_providers">
                {% include "socialaccount/snippets/provider_list.html" with process="login" %}
            </ul>
            <div class="login-or">{% trans 'or' %}</div>
        </div>
        {% include "socialaccount/snippets/login_extra.html" %}
    {% else %}
        <p>{% blocktrans %}If you have not created an account yet, then please
        <a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
    {% endif %}

    <form method="POST" action="{% url 'account_login' %}" class="login pure-form pure-form-stacked validated-form">
    {% csrf_token %}
        <formfields>
            {% include 'accounts/accounts-form.html' %}
            {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
            {% endif %}
            <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot your password?" %}</a>
            <br><br>
            <button class="primaryAction pure-button" type="submit">{% trans "Sign In" %}</button>
        </formfields>
    </form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block orpheus-navbar-logout %}orpheus-navbar-selected{% endblock %}

{% block content %}
<h1>{% trans "Sign Out" %}</h1>

<p>{% trans 'Are you sure you want to sign out?' %}</p>

<form method="post" action="{% url 'account_logout' %}" class="pure-form pure-form-stacked validated-form">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button class="pure-button" type="submit">{% trans 'Sign Out' %}</button>
</form>


{% endblock %}

accounts/templates/accounts/orpheususer_form.html
{% extends "accounts/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans "Account" %}{% endblock %}

{% block body %}
    <form action="" method="post" enctype="multipart/form-data" class="pure-form pure-form-stacked validated-form">
        {% csrf_token %}
        {% include 'orpheus/form-template.html' %}
        <button class="pure-button" type="submit">{% trans 'Submit' %}</button>
    </form>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>

    <form method="POST" action="{% url 'account_change_password' %}" class="password_change pure-form pure-form-stacked validated-form">
        {% csrf_token %}
        {% include 'accounts/accounts-form.html' %}
        <button class="pure-button" type="submit" name="action">{% trans "Change Password" %}</button>
    </form>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends "accounts/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}

    <h1>{% trans "Password Reset" %}</h1>
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}

    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it." %}</p>

    <form method="POST" action="{% url 'account_reset_password' %}" class="password_reset pure-form pure-form-stacked validated-form">
        {% csrf_token %}
        {% include 'accounts/accounts-form.html' %}
        <button class="pure-button" type="submit">{% trans 'Reset My Password' %}</button>
    </form>

    <p>{% blocktrans %}Please contact us if you have any trouble resetting your password.{% endblocktrans %}</p>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "accounts/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}
    <h1>{% trans "Password Reset" %}</h1>
    
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}
    
    <p>{% blocktrans %}We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>
{% endblock %}

accounts/templates/accounts/password_reset_from_key_done.html
{% extends "accounts/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>
    <p>{% trans 'Your password is now changed.' %}</p>
{% endblock %}

accounts/templates/accounts/password_set.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Set Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Set Password" %}</h1>

    <form method="POST" action="{% url 'account_set_password' %}" class="password_set pure-form pure-form-stacked validated-form">
        {% csrf_token %}
        {% include 'accounts/accounts-form.html' %}
        <button class="pure-button" type="submit" name="action">{% trans 'Set Password' %}</button>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}

{% load staticfiles %}
{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Profile" %}{% endblock %}

{% block page_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile.css' %}">
{% endblock %}

{% block orpheus-navbar-profile %}orpheus-navbar-selected{% endblock %}

{% block content %}
    <div class="orpheus-profile-fullname">{{ orpheus_user.full_name }}</div>
    <div class="orpheus-profile-username">{{ orpheus_user.username }}</div>
    <div class="orpheus-profile-info">
        <div class="orpheus-profile-picture">
            <img src="{{ orpheus_user.profile_picture_url }}" alt="avatar">
        </div>
        {% if user.is_authenticated and orpheus_user == user or user.is_staff %}
            <div class="orpheus-profile-edit-controls">
                <a href="{% url 'account_edit' orpheus_user.username %}"><button class="pure-button">{% trans 'Change account info' %}</button></a><br><br>
                <a href="{% url 'account_email' %}"><button class="pure-button">{% trans 'Change E-mail' %}</button></a><br><br>
                <a href="{% url 'account_change_password' %}"><button class="pure-button">{% trans 'Change password' %}</button></a><br><br>
                <a href="{% url 'stats:index' orpheus_user.username %}"><button class="pure-button">{% trans 'Statistics' %}</button></a><br><br>
            </div>
        {% endif %}
    </div>
    <h3>{% trans 'Videos' %}</h3>
    {% if orpheus_user.username == user.username or user.is_staff %}
        <a href="{% url 'videos:add' %}"><button class="pure-button">{% trans 'Add' %}</button></a><br><br>
    {% endif %}

    <div class="orpheus-media-block-container">
        {% for video in user_videos %}
            <div class="orpheus-media-block orpheus-video-block">
                <a href="{% url 'videos:watch' video.id %}">
                    <img src="{{ video.thumbnail_url }}" class="orpheus-media-block-thumbnail orpheus-video-block-thumbnail">
                    {{ video.title }}
                </a>
                {% if orpheus_user.username == user.username or user.is_staff %}
                    <br>
                    <div class="orpheus-profile-media-controls">
                        <a href="{% url 'videos:edit' video.id %}"><button class="pure-button">{% trans 'Edit' %}</button></a>
                        <a href="{% url 'videos:delete' video.id %}"><button class="pure-button">{% trans 'Delete' %}</button></a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <h3>{% trans 'Albums' %}</h3>
    {% if orpheus_user.username == user.username or user.is_staff %}
        <a href="{% url 'music:add-album' %}"><button class="pure-button">{% trans 'Add' %}</button></a><br><br>
    {% endif %}
    <div class="orpheus-media-block-container">
        {% for album in user_albums %}
            <div class="orpheus-media-block orpheus-album-block">
                <a href="{% url 'music:listen' album.id %}">
                    <img src="{{ album.thumbnail_url }}" class="orpheus-media-block-thumbnail orpheus-album-block-thumbnail">
                    {{ album.title }}
                </a>
               {% if orpheus_user.username == user.username or user.is_staff %}
                   <br>
                   <div class="orpheus-profile-media-controls">
                       <a href="{% url 'music:edit-album' album.id %}"><button class="pure-button">{% trans 'Edit' %}</button></a>
                       <a href="{% url 'music:delete-album' album.id %}"><button class="pure-button">{% trans 'Delete' %}</button></a>
                   </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}

{% block orpheus-navbar-signup %}orpheus-navbar-selected{% endblock %}

{% block content %}
<h1>{% trans "Sign Up" %}</h1>

<p>{% blocktrans %}Already have an account? Then please <a href="{{ login_url }}">sign in</a>.{% endblocktrans %}</p>

<form class="signup pure-form pure-form-stacked validated-form" id="signup_form" method="post" action="{% url 'account_signup' %}">
    {% csrf_token %}
    {% include 'accounts/accounts-form.html' %}
    {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
    {% endif %}
    <button class="pure-button" type="submit">{% trans "Sign Up" %} &raquo;</button>
</form>

{% endblock %}

accounts/templates/accounts/signup_closed.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Up Closed" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Up Closed" %}</h1>

<p>{% trans "We are sorry, but the sign up is currently closed." %}</p>
{% endblock %}