media_common/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^upvote/(?P<media_id>[0-9]+)$',
        views.media_upvote_view,
        name='media-upvote'),
    url(r'^downvote/(?P<media_id>[0-9]+)$',
        views.media_downvote_view,
        name='media-downvote'),

    url(r'^comments/get/(?P<media_id>[0-9]+)$',
        views.CommentListAPIView.as_view(),
        name='comments-get'),
    url(r'^comments/post/$',
        views.CommentCreateApiView.as_view(),
        name='comments-post'),
    url(r'^comments/put/(?P<pk>[0-9]+)$',
        views.CommentUpdateAPIView.as_view(),
        name='comments-put'),
    url(r'^comments/delete/(?P<pk>[0-9]+)$',
        views.CommentDeleteAPIView.as_view(),
        name='comments-delete'),
    url(r'^comments/upvote/(?P<comment_id>[0-9]+)$',
        views.comment_upvote_view,
        name='comments-upvote'),
    url(r'^comments/downvote/(?P<comment_id>[0-9]+)$',
        views.comment_downvote_view,
        name='comments-downvote'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.AlbumListenView.as_view(), name='listen'),
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='add-album'),
    url(r'^album/edit/(?P<pk>[0-9]+)$', views.AlbumUpdate.as_view(),
        name='edit-album'),
    url(r'^album/delete/(?P<pk>[0-9]+)$', views.AlbumDelete.as_view(),
        name='delete-album'),
    url(r'^song/add/(?P<album_id>[0-9]+)$', views.SongCreate.as_view(),
        name='add-song'),
    url(r'^song/edit/(?P<pk>[0-9]+)$', views.SongUpdate.as_view(),
        name='edit-song'),
    url(r'^song/delete/(?P<pk>[0-9]+)$', views.SongDelete.as_view(),
        name='delete-song'),
    url(r'^search/$', views.AlbumSearchView.as_view(), name='search'),
    url(r'^frontpage/(?P<page>[0-9]+)$',
        views.get_frontpage_videos,
        name='frontpage'),
]

orpheus/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = i18n_patterns(
    # url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^media/', include('media_common.urls', namespace="media")),
    url(r'^videos/', include('videos.urls', namespace="videos")),
    url(r'^music/', include('music.urls', namespace="music")),
    url(r'^stats/', include('stats.urls', namespace="stats")),
    url(r'^$', views.index, name='index'),
)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

handler404 = 'orpheus.views.page_not_found_view'
handler500 = 'orpheus.views.error_view'
handler403 = 'orpheus.views.permission_denied_view'
handler400 = 'orpheus.views.bad_request_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

media_common/models.py
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from taggit.managers import TaggableManager

from accounts.models import OrpheusUser


class Media(models.Model):
    title = models.CharField(_("Title"), max_length=100)
    description = models.TextField(_("Description"))
    created = models.DateTimeField(_("Created"), default=now)
    user = models.ForeignKey(OrpheusUser, on_delete=models.CASCADE)
    upvoted_by = models.ManyToManyField(OrpheusUser,
                                        blank=True,
                                        related_name="media_upvoted_by")
    downvoted_by = models.ManyToManyField(OrpheusUser,
                                          blank=True,
                                          related_name="media_downvoted_by")
    tags = TaggableManager(blank=True,
                           help_text=_("A list of tags separated by commas or spaces."))

    def __str__(self):
        return self.title

    @property
    def view_count(self):
        return MediaVisit.objects.filter(media=self).count()

    @property
    def upvote_count(self):
        return self.upvoted_by.count()

    @property
    def downvote_count(self):
        return self.downvoted_by.count()

    @property
    def comment_count(self):
        return Comment.objects.filter(media=self).count()


class MediaVisit(models.Model):
    ip = models.CharField(max_length=40)
    media = models.ForeignKey(Media, on_delete=models.CASCADE)
    user = models.ForeignKey(OrpheusUser, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.ip


class Comment(models.Model):
    parent = models.IntegerField(_("Parent"), null=True)
    created = models.DateTimeField(_("Created"), default=now)
    modified = models.DateTimeField(_("Modified"), null=True)
    content = models.TextField(_("Content"))
    fullname = models.TextField(_("Full name"))
    profile_url = models.TextField(_("Profile url"), blank=True)
    profile_picture_url = models.TextField(_("Profile picture url"),
                                           blank=True)
    created_by_admin = models.BooleanField(_("Created by admin"),
                                           default=False)
    created_by_current_user = models.BooleanField(_("Created by current user"),
                                                  default=False)
    upvote_count = models.IntegerField(_("Upvote count"), default=0)
    user_has_upvoted = models.BooleanField(_("User has upvoted"), default=False)
    media = models.ForeignKey(Media, on_delete=models.CASCADE)
    user = models.ForeignKey(OrpheusUser, on_delete=models.CASCADE)
    upvoted_by = models.ManyToManyField(OrpheusUser,
                                        blank=True,
                                        related_name="comment_upvoted_by")

    def __str__(self):
        return "%s %s %s" % (self.pk, self.created, self.user.username)

media_common/views.py
from django.core.cache import cache
from django.db.models import Q, Count
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from django.http import Http404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from pure_pagination import PaginationMixin
from rest_framework import status
from rest_framework.generics import (
    ListAPIView,
    CreateAPIView,
    UpdateAPIView,
    DestroyAPIView
)
from rest_framework.response import Response
from .models import Comment, Media, MediaVisit
from .serializers import CommentSerializer


class MediaIndexView(generic.ListView):

    def get_queryset(self):
        media = Media.objects.all()
        return MediaIndexView.get_frontpage_media(media)

    @staticmethod
    def get_frontpage_media(media, page=1, count=21):
        # Sort by media properties in reversed order of importance
        # sorting with the most important condition last
        media = sorted(media, key=lambda m: m.comment_count, reverse=True)
        media = sorted(media, key=lambda m: m.downvote_count)
        media = sorted(media, key=lambda m: m.upvote_count, reverse=True)
        media = sorted(media, key=lambda m: m.view_count, reverse=True)
        end = page * count
        start = end - count
        return media[start:end]


class MediaDetailView(generic.DetailView):

    def count_views(self):
        # Set nginx header for remote IPs in production
        if 'HTTP_X_REAL_IP' in self.request.META:
            self.request.META['REMOTE_ADDR'] = (
                self.request.META['HTTP_X_REAL_IP'])

        ip = self.request.META['REMOTE_ADDR']
        user = 'anonymous'
        if self.request.user.is_authenticated:
            user = self.request.user.username
        cache_key = "%s:%s:%s" % (self.object.id, user, ip)
        has_viewed = cache.get(cache_key)
        if not has_viewed:
            # Set cache to keep records of ip addresses for an hour
            # to achieve a semi unique view counter
            cache.set(cache_key, True, 60 * 60)
            visit = MediaVisit(ip=ip, media=self.object)
            if self.request.user.is_authenticated:
                visit.user = self.request.user
            visit.save()
        return self.object.view_count

    def get_context_data(self, **kwargs):
        context = super(MediaDetailView, self).get_context_data(**kwargs)
        upvotes = self.object.upvoted_by.filter(pk=self.request.user.pk)
        downvotes = self.object.downvoted_by.filter(pk=self.request.user.pk)
        vote = "none"
        if self.request.user in upvotes:
            vote = 'upvote'
        elif self.request.user in downvotes:
            vote = 'downvote'
        context['current_user_vote'] = vote
        context['upvote_count'] = self.object.upvote_count
        context['downvote_count'] = self.object.downvote_count
        context['view_count'] = self.count_views()
        return context


class MediaSearchView(PaginationMixin, generic.ListView):
    context_object_name = "results"
    paginate_by = 12

    def get_queryset(self):
        query = self.request.GET['query']
        search_keys = query.split()
        result_lists = []
        for key in search_keys:
            result_lists.append(
                self.model.objects.filter(
                    Q(title__icontains=key) |
                    Q(user__username__icontains=key) |
                    Q(user__full_name__icontains=key) |
                    Q(tags__name__in=[key])
                )
            )
        # Create empty queryset and chain results for all search keys
        results = self.model.objects.none()
        for result_list in result_lists:
            results |= result_list

        # Order results by order of appearances in results
        # therefore getting the most relevant result and
        # then exclude all duplicates
        results = (results.annotate(itemcount=Count('id'))
                   .order_by('-itemcount')
                   .distinct())
        return results


def media_upvote_view(request, media_id):
    if not request.user.is_authenticated.value:
        return HttpResponse(status=status.HTTP_403_FORBIDDEN)
    media = Media.objects.get(pk=media_id)
    upvotes = media.upvoted_by.filter(pk=request.user.pk)
    downvotes = media.downvoted_by.filter(pk=request.user.pk)
    if request.user not in upvotes:
        if request.user in downvotes:
            media.downvoted_by.remove(request.user)
        media.upvoted_by.add(request.user)
    else:
        media.upvoted_by.remove(request.user)
    media.save()
    return HttpResponse(status=status.HTTP_200_OK)


def media_downvote_view(request, media_id):
    if not request.user.is_authenticated.value:
        return HttpResponse(status=status.HTTP_403_FORBIDDEN)
    media = Media.objects.get(pk=media_id)
    upvotes = media.upvoted_by.filter(pk=request.user.pk)
    downvotes = media.downvoted_by.filter(pk=request.user.pk)
    if request.user not in downvotes:
        if request.user in upvotes:
            media.upvoted_by.remove(request.user)
        media.downvoted_by.add(request.user)
    else:
        media.downvoted_by.remove(request.user)
    media.save()
    return HttpResponse(status=status.HTTP_200_OK)


class MediaCreate(CreateView):
    model = Media
    fields = ['title', 'description', 'tags']

    def form_valid(self, form):
        media = form.save(commit=False)
        media.user = self.request.user
        media.save()
        # Without this next line the tags won't be saved.
        form.save_m2m()
        if self.request.is_ajax():
            return HttpResponse(media.get_absolute_url())
        else:
            return super(MediaCreate, self).form_valid(form)


class MediaUpdate(UpdateView):
    model = Media
    fields = ['title', 'description', 'tags']

    def form_valid(self, form):
        media = form.save(commit=False)
        media.save()
        # Without this next line the tags won't be saved.
        form.save_m2m()
        if self.request.is_ajax():
            return HttpResponse(media.get_absolute_url())
        else:
            return super(MediaUpdate, self).form_valid(form)

    def get_object(self, queryset=None):
        media = super(MediaUpdate, self).get_object()
        if (not media.user == self.request.user and
                not self.request.user.is_staff):
            raise Http404
        return media


class MediaDelete(DeleteView):
    model = Media

    def get_success_url(self):
        return reverse_lazy('account_profile',
                            kwargs={'username': self.object.user.username})

    def get_object(self, queryset=None):
        media = super(MediaDelete, self).get_object()
        if (not media.user == self.request.user and
                not self.request.user.is_staff):
            raise Http404
        return media


class CommentListAPIView(ListAPIView):
    serializer_class = CommentSerializer

    def get_queryset(self):
        media_id = self.kwargs['media_id']
        comments = Comment.objects.filter(media_id=media_id)
        comments = comments.filter(
            Q(parent__in=comments) |
            Q(parent__isnull=True)
        )
        for comment in comments:
            comment.created_by_current_user = (
                comment.user == self.request.user
            )
            comment.created_by_admin = comment.user.is_admin
            comment.user_has_upvoted = (
                self.request.user in
                comment.upvoted_by.filter(pk=self.request.user.pk)
            )
            comment.profile_picture_url = comment.user.profile_picture_url
            comment.profile_url = reverse(
                'account_profile',
                kwargs={'username': comment.user.username}
            )
        queryset = comments
        return queryset


class CommentCreateApiView(CreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


class CommentUpdateAPIView(UpdateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


class CommentDeleteAPIView(DestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def perform_destroy(self, instance):
        if instance.user == self.request.user or self.request.user.is_staff:
            return super(CommentDeleteAPIView, self).perform_destroy(instance)
        else:
            return Response(status=status.HTTP_403_FORBIDDEN)


def comment_upvote_view(request, comment_id):
    if not request.user.is_authenticated.value:
        return HttpResponse(status=status.HTTP_403_FORBIDDEN)

    comment = Comment.objects.get(pk=comment_id)
    queryset = comment.upvoted_by.filter(pk=request.user.pk)
    if request.user not in queryset:
        comment.upvoted_by.add(request.user)
        comment.user_has_upvoted = True
        comment.upvote_count += 1
        comment.save()
        return HttpResponse(status=status.HTTP_200_OK)
    return HttpResponse(status=status.HTTP_400_BAD_REQUEST)


def comment_downvote_view(request, comment_id):
    if not request.user.is_authenticated.value:
        return HttpResponse(status=status.HTTP_403_FORBIDDEN)

    comment = Comment.objects.get(pk=comment_id)
    queryset = comment.upvoted_by.filter(pk=request.user.pk)
    if request.user in queryset:
        comment.upvoted_by.remove(request.user)
        comment.user_has_upvoted = False
        comment.upvote_count -= 1
        comment.save()
        return HttpResponse(status=status.HTTP_200_OK)
    return HttpResponse(status=status.HTTP_400_BAD_REQUEST)

media_common/templates/media_common/base-common.html
{% extends "orpheus/master.html" %}
{% load staticfiles %}
{% load i18n %}


{% block css %}
    <link rel="stylesheet" href="{% static 'media_common/css/base-common.css' %}" />
    {% block media_css %}{% endblock %}
{% endblock %}

{% block js%}
    <script src="{% static 'media_common/js/search-form-validation.js' %}"></script>
    {% block media_js %}{% endblock %}
{% endblock %}

{% block body %}
    <form role="search" method="get" action="{% block search_action %}{% endblock %}" class="pure-form">
        <div class="orpheus-search-form">
            <input class="orpheus-search-bar" title="Search" type="text" name="query" value="{{ request.GET.query }}"/>
            <button class="pure-button" type="submit">{% trans 'Search' %}</button>
        </div>
    </form>
    {% block media_common_body %}{% endblock %}
{% endblock %}

media_common/templates/media_common/comments-initialization.html
{% load staticfiles %}
{% load i18n %}

<script src="{% static 'orpheus/addons/comments/jquery-comments.js' %}"></script>
<script>
    var login_url = '{% url 'account_login' %}';
    var logged_in = {{ user.is_authenticated|yesno:"true,false" }};

    $('#orpheus-comments-container').comments({
        {% if not user.is_authenticated %}
            enableReplying: false,
        {% else  %}
            profilePictureURL: "{{ user.profile_picture_url }}",
            {% if user.is_staff %}
                currentUserIsAdmin: true,
            {% endif %}
        {% endif %}
        textareaPlaceholderText: "{% trans 'Add a comment' %}",
        newestText: "{% trans 'Newest' %}",
        oldestText: "{% trans 'Oldest' %}",
        popularText: "{% trans 'Popular' %}",
        attachmentsText: "{% trans 'Attachments' %}",
        sendText: "{% trans 'Send' %}",
        replyText: "{% trans 'Reply' %}",
        editText: "{% trans 'Edit' %}",
        editedText: "{% trans 'Edited' %}",
        youText: "{{ user.full_name }}",
        saveText: "{% trans 'Save' %}",
        deleteText: "{% trans 'Delete' %}",
        viewAllRepliesText: "{% trans 'View all __replyCount__ replies' %}",
        hideRepliesText: "{% trans 'Hide replies' %}",
        noCommentsText: "{% trans 'No comments' %}",
        noAttachmentsText: "{% trans 'No attachments' %}",
        attachmentDropText: "{% trans 'Drop files here' %}",
        getComments: function(success, error) {
            $.ajax({
                type: 'get',
                url: '{% url 'media:comments-get' media.id %}',
                success: function(commentsArray) {
                    success(commentsArray);
                },
                error: error
            });
        },
        postComment: function(commentJSON, success, error) {
            {% if not user.is_authenticated %}
                if (!logged_in) {
                    $(location).attr('href', login_url);
                    return;
                }
            {% endif %}
            commentJSON['media_id'] = {{ media.id }};
            var data = JSON.stringify(commentJSON);
            $.ajax({
                type: 'post',
                dataType: "json",
                contentType: "application/json",
                url: '{% url 'media:comments-post' %}',
                data: data,
                success: function(comment) {
                    success(comment)
                },
                error: error
            });
        },
        putComment: function(commentJSON, success, error) {
            commentJSON['modified'] = new Date(commentJSON['modified']);
            commentJSON['media_id'] = {{ media.id }};

            var comment_id = commentJSON['id'];
            var url = '{% url 'media:comments-put' '0' %}';
            url = url.replace('0', comment_id);

            var data = JSON.stringify(commentJSON);
            $.ajax({
                type: 'put',
                dataType: "json",
                contentType: "application/json",
                url: url,
                data: data,
                success: function(comment) {
                    success(comment)
                },
                error: error
            });
        },
        deleteComment: function(commentJSON, success, error) {
            var comment_id = commentJSON['id'];
            var url = '{% url 'media:comments-delete' '0' %}';
            url = url.replace('0', comment_id);
            $.ajax({
                type: 'delete',
                url: url,
                success: success,
                error: error
            });
        },
        upvoteComment: function(commentJSON, success, error) {
            {% if not user.is_authenticated %}
                var upvote_count = $('.highlight-font > span');
                $('.highlight-font').removeClass("highlight-font");
                upvote_count.text(parseInt(upvote_count.text()) - 1);
                if (!logged_in) {
                    $(location).attr('href', '{% url 'account_login' %}');
                    return;
                }
            {% endif %}
            var comment_id = commentJSON['id'];
            var upvote_url = '{% url 'media:comments-upvote' '0' %}';
            upvote_url = upvote_url.replace('0', comment_id);
            var downvote_url = '{% url 'media:comments-downvote' '0' %}';
            downvote_url = downvote_url.replace('0', comment_id);
            if(commentJSON.user_has_upvoted) {
                $.ajax({
                    type: 'post',
                    url: upvote_url,
                    success: function() {
                        success(commentJSON);
                    },
                    error: error
                });
            } else {
                $.ajax({
                    type: 'post',
                    url: downvote_url,
                    success: function() {
                        success(commentJSON);
                    },
                    error: error
                });
            }
        }
    });
    {% if not user.is_authenticated %}
        $('.commenting-field').remove();
    {% endif %}
</script>

media_common/templates/media_common/frontpage-load-more.html
<script>
    var page_to_load = 2;

    $('.frontpage-load-more').click(function(success, error) {
        var url = '{{ media_list_url }}';
        url = url.replace('0', '' + page_to_load);
        $.ajax({
            type: 'get',
            url: url,
            success: function(response) {
                $('.orpheus-media-block-container').append(response);
                page_to_load += 1;
            },
            error: error
        });
    });
</script>

media_common/templates/media_common/media_info_box.html
{% load i18n %}
<div class="orpheus-media-info-top">
    <a href="{% url 'account_profile' media.user %}">
        <div class="orpheus-media-info-left">
            <div class="orpheus-profile-picture">
                <img src="{{ media.user.profile_picture_url }}" alt="avatar">
            </div>
            <div class="orpheus-profile-name">
                {{ media.user.full_name }}
            </div>
        </div>
    </a>
    <div class="orpheus-media-info-right">
        <div>
            {% include 'media_common/view-count-block.html' %}
        </div>
        <div>
            {% include 'media_common/voting-block.html' %}
        </div>
    </div>
</div>
<div class="orpheus-media-info-bottom">
    <div class="orpheus-media-description">
        <div class="orpheus-media-created">{% trans "Published" %}: {{ media.created.date }}</div>
        <div>{{ media.description }}</div>
    </div>
    <div class="orpheus-media-tags">
        {% trans "Tags" %}:
        {% for tag in media.tags.all %}
            <span class="orpheus-media-tag"><a href="{{ search_url }}?query={{ tag.name }}">{{ tag.name }}</a></span>
        {% empty %}
            <span class="orpheus-media-tag">{% trans "none" %}</span>
        {% endfor %}
    </div>
</div>

media_common/templates/media_common/pagination.html
{% load i18n %}
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">
            <button class="pure-button">&lsaquo;&lsaquo;</button>
        </a>
    {% else %}
        <span class="disabled prev">
            <button class="pure-button" disabled>&lsaquo;&lsaquo;</button>
        </span>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page">
                    <button class="pure-button pure-button-active">{{ page }}</button>
                </span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">
                    <button class="pure-button ">{{ page }}</button>
                </a>
            {% endifequal %}
        {% else %}
            <span class="ellipses">...</span>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="?{{ page_obj.next_page_number.querystring }}" class="next">
            <button class="pure-button">&rsaquo;&rsaquo;</button>
        </a>
    {% else %}
        <span class="disabled next">
            <button class="pure-button" disabled>&rsaquo;&rsaquo;</button>
        </span>
    {% endif %}
</div>

media_common/templates/media_common/view-count-block.html
{% load i18n %}
{% trans 'Views' %}: {{ view_count }}<br>

media_common/templates/media_common/voting-block.html
<br>
<i class="orpheus-media-upvote fa fa-thumbs-up" aria-hidden="true"></i>
<span class="orpheus-media-upvote-count">{{ upvote_count }}</span>
&nbsp;
<i class="orpheus-media-downvote fa fa-thumbs-down" aria-hidden="true"></i>
<span class="orpheus-media-downvote-count">{{ downvote_count }}</span>
<br>

media_common/templates/media_common/voting-initialization.html
<script>
    var login_url = '{% url 'account_login' %}';
    var logged_in = {{ user.is_authenticated|yesno:"true,false" }};

    var media_upvote_button = $('.orpheus-media-upvote');
    var media_downvote_button = $('.orpheus-media-downvote');

    var media_upvote_count = $('.orpheus-media-upvote-count');
    var media_downvote_count = $('.orpheus-media-downvote-count');

    function change_counter(element, val) {
        element.text(parseInt(element.text()) + val);
    }

    media_upvote_button.click(function(){
        {% if not user.is_authenticated %}
            if (!logged_in) {
                $(location).attr('href', login_url);
                return;
            }
        {% endif %}
        $.ajax({
            type: 'get',
            url: '{% url 'media:media-upvote' media.id %}',
            success: function() {
                if (media_upvote_button.hasClass('orpheus-upvote-active')) {
                    media_upvote_button.removeClass('orpheus-upvote-active');
                    change_counter(media_upvote_count, -1);
                } else {
                    media_upvote_button.addClass('orpheus-upvote-active');
                    change_counter(media_upvote_count, 1);
                }
                if (media_downvote_button.hasClass('orpheus-downvote-active')) {
                    change_counter(media_downvote_count, -1);
                }
                media_downvote_button.removeClass('orpheus-downvote-active');
            },
            error: function(e) {}
        });
    });
    media_downvote_button.click(function(){
        {% if not user.is_authenticated %}
            if (!logged_in) {
                $(location).attr('href', login_url);
                return;
            }
        {% endif %}
        $.ajax({
            type: 'get',
            url: '{% url 'media:media-downvote' media.id %}',
            success: function(response) {
                if (media_downvote_button.hasClass('orpheus-downvote-active')) {
                    media_downvote_button.removeClass('orpheus-downvote-active');
                    change_counter(media_downvote_count, -1);
                } else {
                    media_downvote_button.addClass('orpheus-downvote-active');
                    change_counter(media_downvote_count, 1);
                }
                if (media_upvote_button.hasClass('orpheus-upvote-active')) {
                    change_counter(media_upvote_count, -1);
                }
                media_upvote_button.removeClass('orpheus-upvote-active');
            },
            error: function() {}
        });
    });

    {% if current_user_vote == 'upvote' %}
        media_upvote_button.addClass('orpheus-upvote-active');
    {% elif current_user_vote == 'downvote' %}
        media_downvote_button.addClass('orpheus-downvote-active');
    {% endif %}
</script>