music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.AlbumListenView.as_view(), name='listen'),
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='add-album'),
    url(r'^album/edit/(?P<pk>[0-9]+)$', views.AlbumUpdate.as_view(),
        name='edit-album'),
    url(r'^album/delete/(?P<pk>[0-9]+)$', views.AlbumDelete.as_view(),
        name='delete-album'),
    url(r'^song/add/(?P<album_id>[0-9]+)$', views.SongCreate.as_view(),
        name='add-song'),
    url(r'^song/edit/(?P<pk>[0-9]+)$', views.SongUpdate.as_view(),
        name='edit-song'),
    url(r'^song/delete/(?P<pk>[0-9]+)$', views.SongDelete.as_view(),
        name='delete-song'),
    url(r'^search/$', views.AlbumSearchView.as_view(), name='search'),
    url(r'^frontpage/(?P<page>[0-9]+)$',
        views.get_frontpage_videos,
        name='frontpage'),
]

orpheus/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = i18n_patterns(
    # url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^media/', include('media_common.urls', namespace="media")),
    url(r'^videos/', include('videos.urls', namespace="videos")),
    url(r'^music/', include('music.urls', namespace="music")),
    url(r'^stats/', include('stats.urls', namespace="stats")),
    url(r'^$', views.index, name='index'),
)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

handler404 = 'orpheus.views.page_not_found_view'
handler500 = 'orpheus.views.error_view'
handler403 = 'orpheus.views.permission_denied_view'
handler400 = 'orpheus.views.bad_request_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.VideoWatchView.as_view(), name='watch'),
    url(r'^add/$', views.VideoCreate.as_view(), name='add'),
    url(r'^edit/(?P<pk>[0-9]+)$', views.VideoUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>[0-9]+)$',
        views.VideoDelete.as_view(),
        name='delete'),
    url(r'^search/$', views.VideoSearchView.as_view(), name='search'),
    url(r'^frontpage/(?P<page>[0-9]+)$',
        views.get_frontpage_videos,
        name='frontpage'),
]

videos/models.py
import os
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django_cleanup.signals import cleanup_post_delete

from accounts.models import OrpheusUser
from media_common.models import Media
from orpheus.settings import STATIC_URL, MEDIA_ROOT
from orpheus.utils import remove_empty_dir


def video_upload_path(instance, filename):
    return os.path.join("videos/videos/%s/" % instance.id, filename)


def caption_upload_path(instance, filename):
    return os.path.join("videos/captions/%s/" % instance.id, filename)


def thumbnail_upload_path(instance, filename):
    return os.path.join("videos/thumbnails/%s/" % instance.id, filename)


class Video(Media):
    source = models.FileField(_("Source"), upload_to=video_upload_path)
    captions = models.FileField(_("Captions"),
                                upload_to=caption_upload_path,
                                blank=True)
    thumbnail = models.FileField(_("Thumbnail"),
                                 upload_to=thumbnail_upload_path,
                                 blank=True)

    def get_absolute_url(self):
        return reverse('videos:watch', kwargs={'pk': self.pk})

    @property
    def thumbnail_url(self):
        if self.thumbnail and hasattr(self.thumbnail, 'url'):
            return self.thumbnail.url
        else:
            return os.path.join(STATIC_URL, 'videos/img/video-default.jpg')


# Receive the pre_delete signal and delete the files
# associated with the model instance.
@receiver(post_delete, sender=Video)
def video_delete(sender, instance, **kwargs):
    cleanup_post_delete.send(sender)
    remove_empty_dir(os.path.join(
        MEDIA_ROOT,
        video_upload_path(instance, "")))
    remove_empty_dir(os.path.join(
        MEDIA_ROOT,
        caption_upload_path(instance, "")))
    remove_empty_dir(os.path.join(
        MEDIA_ROOT,
        thumbnail_upload_path(instance, "")))

videos/views.py
from django.shortcuts import render

from media_common.views import (
    MediaSearchView,
    MediaDetailView,
    MediaCreate,
    MediaUpdate,
    MediaDelete,
    MediaIndexView
)
from .models import Video


class IndexView(MediaIndexView):
    template_name = 'videos/index.html'
    context_object_name = 'all_videos'

    def get_queryset(self):
        videos = Video.objects.all()
        return MediaIndexView.get_frontpage_media(videos)


def get_frontpage_videos(request, page):
    videos = Video.objects.all()
    page = int(page)
    all_videos = MediaIndexView.get_frontpage_media(videos, page)
    return render(request, 'videos/video-list.html', {'all_videos': all_videos})


class VideoWatchView(MediaDetailView):
    model = Video
    template_name = 'videos/watch.html'


class VideoCreate(MediaCreate):
    model = Video
    fields = ['title', 'description', 'source', 'thumbnail', 'captions', 'tags']


class VideoUpdate(MediaUpdate):
    model = Video
    fields = ['title', 'description', 'thumbnail', 'captions', 'tags']


class VideoDelete(MediaDelete):
    model = Video


class VideoSearchView(MediaSearchView):
    template_name = 'videos/search-result.html'
    model = Video

videos/templates/videos/base.html
{% extends "media_common/base-common.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans 'Videos' %}{% endblock %}

{% block media_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'videos/css/base.css' %}" />
    {% block page_css %}{% endblock %}
{% endblock %}


{% block media_js%}
    {% block page_js %}{% endblock %}
{% endblock %}


{% block orpheus-navbar-videos %}orpheus-navbar-selected{% endblock %}


{% block media_common_body %}
    {% block page_body %}{% endblock %}
{% endblock %}


{% block search_action %}{% url 'videos:search' %}{% endblock %}

videos/templates/videos/index.html
{% extends "videos/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page_css %}
{% endblock %}

{% block page_js %}
        {% url 'videos:frontpage' 0 as video_list_url %}
        {% include 'media_common/frontpage-load-more.html' with media_list_url=video_list_url %}
{% endblock %}

{% block page_body %}
    <div class="orpheus-media-block-container">
        {% include 'videos/video-list.html' %}
    </div>
    <button class="pure-button frontpage-load-more">{% trans "Load more" %}</button>
{% endblock %}

videos/templates/videos/search-result.html
{% extends "videos/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans 'Video search' %}{% endblock %}

{% block page_css %}
{% endblock %}

{% block page_js %}
{% endblock %}

{% block page_body %}
    <h3>{% blocktrans %}Results for {% endblocktrans %}"{{ request.GET.query }}":</h3>
    {% include 'media_common/pagination.html' %}
    <div class="orpheus-media-block-container">
        {% include 'videos/video-list.html' with all_videos=results %}
    </div>
    {% if results.count == 0 %}
        <p>{% blocktrans %}No videos found.{% endblocktrans %}</p>
    {% endif %}
    {% include 'media_common/pagination.html' %}
{% endblock %}

videos/templates/videos/video-list.html
{% for video in all_videos %}
    <div class="orpheus-media-block orpheus-video-block">
        <a href="{% url 'videos:watch' video.id %}">
            <img src="{{ video.thumbnail_url }}" class="orpheus-media-block-thumbnail orpheus-video-block-thumbnail">
            <b>{{ video.title }}</b>
        </a>
        <br>
        <a href="{% url 'account_profile' video.user %}"><i>{{ video.user.full_name }}</i></a>
    </div>
{% endfor %}

videos/templates/videos/video_confirm_delete.html
{% extends "videos/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans "Delete video" %}{% endblock %}

{% block page_body %}
    {% include 'orpheus/form-confirm-delete.html' %}
{% endblock %}

videos/templates/videos/video_form.html
{% extends "videos/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans 'Video' %}{% endblock %}

{% block page_body %}
    <form action="" method="post" enctype="multipart/form-data" class="pure-form pure-form-stacked validated-form">
        {% csrf_token %}
        {% include 'orpheus/form-template.html' %}
        <button class="pure-button" type="submit">{% trans 'Submit' %}</button>
    </form>
{% endblock %}

videos/templates/videos/watch.html
{% extends "videos/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{{ video.title }}{% endblock %}

{% block page_css %}
    <link rel="stylesheet" href="{% static 'orpheus/addons/player/mediaelementplayer.min.css' %}" />
    <link rel="stylesheet" href="{% static 'orpheus/addons/comments/jquery-comments.css' %}" />
    <link rel="stylesheet" href="{% static 'videos/css/watch.css' %}" />
{% endblock %}

{% block page_js %}
    <script src="{% static 'orpheus/addons/player/mediaelement-and-player.js' %}"></script>
    {% with video as media %}
        {% include 'media_common/voting-initialization.html' %}
        {% include 'media_common/comments-initialization.html' %}
    {% endwith %}
    <script src="{% static 'videos/js/watch.js' %}"></script>
{% endblock %}

{% block page_body %}
    <h1>{{ video.title }}</h1>
    {% if video.user == user or user.is_staff %}
        <a href="{% url 'videos:edit' video.id %}"><button class="pure-button">{% trans 'Edit video' %}</button></a>
        <a href="{% url 'videos:delete' video.id %}"><button class="pure-button">{% trans 'Delete video' %}</button></a>
        <br><br>
    {% endif %}
    <div class="orpheus-video-container">
        <video id="player" controls="controls" style="width:100%; height: 100%;">
            <source src="{{ video.source.url }}" type="video/mp4">
            {% if video.captions %}
                <track kind="subtitles" src="{{ video.captions.url }}" srclang="en" />
            {% endif %}
            <p>{% blocktrans %}Your browser does not support this video.{% endblocktrans %}</p>
        </video>
    </div>
    {% url 'videos:search' as search_url %}
    {% include 'media_common/media_info_box.html' with media=video search_url=search_url %}
    <div id="orpheus-comments-container"></div>
{% endblock %}